### ISSUE TITLE
Consider using ultralyics

### ISSUE THREAD

**Issue by AyushExel** [mikel-brostrom/yolov8_tracking#684]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar enhancement requests.

### Description

Hey @mikel-brostrom , we just released the Ultralytics framework. https://github.com/ultralytics/ultralytics
It comes with YOLOv8 but we've built it as a framework so it can support any type of model. I thought it might be useful for this project as you currently have to maintain a fork of v5. You can instead build the same features with ultralytics framework.
Check out the python usage and customization section of the docs -> https://docs.ultralytics.com/sdk/
Give it a try in an experimental branch. I'd be happy to address any feedback you have.

**Comment by mikel-brostrom** [comment]
Hi @AyushExel

> we just released the Ultralytics framework. https://github.com/ultralytics/ultralytics

Congratulations! Looks awesome. Will let you know when I try it out :smile:

**Comment by mikel-brostrom** [comment]
I have yolov8 working with all the trackers now, @AyushExel . The integration using the pip package was not possible for this specific case as the tracking functionality has to be within the `engine.predictor` dataset loop:

https://github.com/ultralytics/ultralytics/blob/583eac0e8040f0bc8ef4d7a7976f8f7e1cf5a771/ultralytics/yolo/engine/predictor.py#L164

I ended up updating the submodule :smile:

**Comment by AyushExel** [comment]
@mikel-brostrom could you hold on for 2 days? We've got this working which'll provide a nice python interface for results

**Comment by mikel-brostrom** [comment]
Nice! Let me know when this is in place :smile:

**Comment by AyushExel** [comment]
@mikel-brostrom hey the change is live! with a dedicated results api https://docs.ultralytics.com/predict/

**Comment by AyushExel** [comment]
@mikel-brostrom hey let me know if you have any questions about the usage. We'd like to support this project directly through the package because this is one of the reasons we released the pip package.

**Comment by mikel-brostrom** [comment]
Yup, I tried it out. The fundamental problem is still there. The tracking functionality has to be within the `engine.predictor`'s dataset loop:

https://github.com/ultralytics/ultralytics/blob/583eac0e8040f0bc8ef4d7a7976f8f7e1cf5a771/ultralytics/yolo/engine/predictor.py#L164

By doing this:

```python
results = model.predict(source="0", show=False) # Display preds. Accepts all YOLO predict arguments
for i, result in enumerate(results):
    boxes = result.boxes # Boxes object for bbox outputs
    masks = result.masks # Masks object for segmenation masks outputs
    probs = result.probs # Class probabilities for classification outputs
    print(i)
```

I have to wait for the stream to be closed in order to access the results. Is there maybe a way of achieving this, that I don't know about?

**Comment by AyushExel** [comment]
@mikel-brostrom can you try running the same code by passing `stream=True` argument?

**Comment by mikel-brostrom** [comment]
Smh... Ok , my bad. Looking into this right away :smile:

**Comment by mikel-brostrom** [comment]
Would need the original images as well from the dataloader @AyushExel ... For the trackers that uses appearance for matching

**Comment by AyushExel** [comment]
@mikel-brostrom I can make sure that it is achievable if it's not currently. Can you just provide a pseidocode of what the callback should access and return?

**Comment by mikel-brostrom** [comment]
Have not found callback functionality for [predict](https://docs.ultralytics.com/reference/base_pred/) so not sure if this is solvable atm. Tried so synthesize what is relevant to make it work. Without giving it too much of a thought:

```python
for batch in dataloder:

        # im0s has to be passed to certain trackers for appearance description extraction
        # path is used for custom path handling
        path, im, im0s, _, _ = batch  

        yolo_results = yolov8(im)

        for i, yolo_result in each enumerate(yolo_results):  # for results from each stream

                p = path[i]
                im0s = im0s[i]

                tracking_results[i] = trackers[i].update(yolo_result, im0)

                for j, tracking_result in enumerate(tracking_results[i]):  # for each tracking predicted bbox on each stream

                        yolov8_annotator.box_label(tracking_result, im0)
                        ...
```

**Comment by AyushExel** [comment]
Ok thanks! I'll think if a nice interface to enable this usage and get back

**Comment by mikel-brostrom** [comment]
Good work on the interface for this @AyushExel . One question. Will it be possible to access `predictor` information  such as the number sources (`bs`) before the detection actually start. In this repo some functionality is be dependent on this. One tracker is started for each stream.

**Comment by AyushExel** [comment]
@mikel-brostrom you can get the source as - `predictor.args.source` . But I'm not sure that'll suffice your use case. Let me know if I missed the point :)

**Comment by mikel-brostrom** [comment]
```python
from ultralytics.yolo.engine.model import YOLO

def on_predict_start(predictor):
    print('on_predict_start', type(predictor))
    print(predictor.bs)
    print(predictor.args.bs)
    
def on_predict_batch_end(predictor):
    # results -> List[batch_size]
    path, im, im0s, vid_cap, s = predictor.batch
    bs = [predictor.bs for i in range(0, len(path))]
    predictor.results = zip(predictor.results, im0s, bs)
         
def test_callback():
    model = YOLO("yolov8n.pt")
    model.add_callback("on_predict_start", on_predict_start)
    model.add_callback("on_predict_batch_end", on_predict_batch_end)
    results = model.predict(source="0", show=False, stream=True)
    for i, (result, im0, bs) in enumerate(results):
        print(bs)
        boxes = result.boxes  # Boxes object for bbox outputs
        masks = result.masks  # Masks object for segmenation masks outputs
        probs = result.probs  # Class probabilities for classification outputs
    
test_callback()
```

gives me:

```bash
on_predict_start <class 'ultralytics.yolo.v8.detect.predict.DetectionPredictor'>
None
Traceback (most recent call last):
  File "new.py", line 39, in <module>
    test_callback()
  File "new.py", line 23, in test_callback
    for i, (result, im0, bs) in enumerate(results):
  File "/home/mikel.brostrom/ultralytics/ultralytics/yolo/engine/predictor.py", line 167, in stream_inference
    self.run_callbacks("on_predict_start")
  File "/home/mikel.brostrom/ultralytics/ultralytics/yolo/engine/predictor.py", line 286, in run_callbacks
    callback(self)
  File "new.py", line 7, in on_predict_start
    print(predictor.args.bs)
AttributeError: 'IterableSimpleNamespace' object has no attribute 'bs'
```

**Comment by mikel-brostrom** [comment]
But ok, the source can be counted from `predictor.args`

**Comment by mikel-brostrom** [comment]
My source files is a txt with two video paths 

```python
from ultralytics.yolo.engine.model import YOLO

def on_predict_start(predictor):
    print('on_predict_start', type(predictor))
    print(predictor.bs)
    print(predictor.args.source)
    
def on_predict_batch_end(predictor):
    # results -> List[batch_size]
    path, im, im0s, vid_cap, s = predictor.batch
    bs = [predictor.bs for i in range(0, len(path))]
    predictor.results = zip(predictor.results, im0s, bs)
         
def test_callback():
    model = YOLO("yolov8n.pt")
    model.add_callback("on_predict_start", on_predict_start)
    model.add_callback("on_predict_batch_end", on_predict_batch_end)
    results = model.predict(source="source.txt", show=False, stream=True)
    for i, (result, im0, bs) in enumerate(results):
        print(bs)
        boxes = result.boxes  # Boxes object for bbox outputs
        masks = result.masks  # Masks object for segmenation masks outputs
        probs = result.probs  # Class probabilities for classification outputs
    
test_callback()
```

This returns:

```bash
on_predict_start <class 'ultralytics.yolo.v8.detect.predict.DetectionPredictor'>
None
ultralytics/assets/
```

so cannot count the number of sources from there

**Comment by AyushExel** [comment]
@mikel-brostrom can you point me t the current repo where you're multiple sources? I don't use multiple sources ever so I might not be getting you but but if you point me to the usage I'll add if to the repo

**Comment by AyushExel** [comment]
It is this https://github.com/mikel-brostrom/yolov8_tracking/blob/master/track.py#L119

**Comment by mikel-brostrom** [comment]
Yes, in ultralytics repo this can be found here:

https://github.com/ultralytics/ultralytics/blob/936414c615bb8635f081b36b98641aac0ed17e64/ultralytics/yolo/engine/predictor.py#L125

**Comment by mikel-brostrom** [comment]
Just so that we keep track of what is going on. Example on how to set up everything making a priori Yolov8 info available before going into the inference loop: https://github.com/ultralytics/ultralytics/blob/7a072ad25c40b263af9a5ff7559252a8d7d7d243/tests/test_python.py

**Comment by mikel-brostrom** [comment]
Still need functionality for customize what is shown on the image

**Comment by AyushExel** [comment]
Okay I'll get this one merges first and then work on supporting high level interface for annotator

**Comment by mikel-brostrom** [comment]
Thank you for the effort @AyushExel. I bet you have enough with the trackers on your side. Good luck :smile:
